script: "bin/rake --trace"
bundler_args: "--binstubs --without development"
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
before_script:
  - "rake db:create:all ; rake db:migrate; rake db:test:prepare"
  
